### ISSUE TITLE
Too many shadows for single object (macOS)

### ISSUE THREAD

**Issue by hiroMTB** [arturoc/ofxShadowMap#5]
![Screen Shot 2019-08-01 at 4 57 36 PM](https://user-images.githubusercontent.com/193280/62307903-c082ef80-b484-11e9-9d41-3dedc3ca3977.png)

Hello Arturo, I noticed a shadow on the ground looks strange like an image above. It looks all of them are different as if a lot of objects stand on different position.
I thought this is because of fbo settings but could not find a solution.
Any idea where to check? I'm on macOS, oF master.

Thanks for this addon anyway.

**Comment by arturoc** [comment]
i can imagine the frustum for that light is too small so it doesn't cover the whole scene and the texture is set to GL_REPEAT so you get a repetition of the same texture. setting the texture to GL_CLAMP shoulre remove the repetition but if you want shadows in all that area you'll need a much bigger frustum which will loose precision of course

**Comment by hiroMTB** [comment]
Thanks!
I will go for bigger frustum.

* I also see "Peter-panning" issue, I will try to look for that too.
